Configuration of mysql done (except on windows)

diff --git a/packages/dbdrivers/mysql/configure b/packages/dbdrivers/mysql/configure
--- a/packages/dbdrivers/mysql/configure
+++ b/packages/dbdrivers/mysql/configure
@@ -12,8 +12,8 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
-  --with-odbc-libdir=DIR	   the directory where the ODBC library lives
-  --with-odbc-incdir=DIR	   the directory of ODBC include files
+  --with-mysql-libdir=DIR	   the directory where the MySQL library lives
+  --with-mysql-incdir=DIR	   the directory of MySQL include files
    "
 
 # Initialize some variables set by options.
@@ -455,7 +455,7 @@ echo > confdefs.h
 
 # A filename unique to this package, relative to the directory that
 # configure is in, which we can look for to find out if srcdir is correct.
-ac_unique_file=odbc_driver_config.P
+ac_unique_file=mysql_driver_config.P
 
 # Find the source files, if location was not specified.
 if test -z "$srcdir"; then
@@ -528,9 +528,9 @@ fi
 
 SHELL=/bin/sh
 
-# Check whether --with-odbc or --without-odbc was given.
-if test "${with_odbc+set}" = set; then
-  withval="$with_odbc"
+# Check whether --with-mysql or --without-mysql was given.
+if test "${with_mysql+set}" = set; then
+  withval="$with_mysql"
   :
 fi
 
@@ -603,37 +603,37 @@ fi
 # make sure new files are readable 
 umask 022
 
-/bin/rm config.cache
+\rm config.cache
 
-with_odbc=
-odbc_error=
+with_mysql=
+mysql_error=
 
-if test -z "$with_odbc_libdir" ; then
-   libdir=
+if test -z "$with_mysql_libdir" ; then
+   libdir="/usr/lib/mysql"
 else
-   libdir=$with_odbc_libdir
+   libdir=$with_mysql_libdir
 fi
-if test -z "$with_odbc_incdir" ; then
-   incdir=
+if test -z "$with_mysql_incdir" ; then
+   incdir="/usr/include/mysql"
 else
-   incdir=$with_odbc_incdir
+   incdir=$with_mysql_incdir
 fi
 
-# check if libodbc.so can be found
-# If the ODBC library is missing, set odbc_error
-# If libodbc.so is not in a standard place, we must use --with-odbc-libdir
-if test -n "$with_odbc_libdir" ; then
-   LDFLAGS="-L${with_odbc_libdir} ${LDFLAGS}"
+# check if libmysqlclient.so can be found
+# If the MySQL library is missing, set mysql_error
+# If libmysqlclient.so is not in a standard place, we must use --with-mysql-libdir
+if test -n "$libdir" ; then
+   LDFLAGS="-L${libdir} ${LDFLAGS}"
 fi
 
-echo $ac_n "checking for  in -lodbc""... $ac_c" 1>&6
-echo "configure:631: checking for  in -lodbc" >&5
-ac_lib_var=`echo odbc'_' | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for  in -lmysqlclient""... $ac_c" 1>&6
+echo "configure:631: checking for  in -lmysqlclient" >&5
+ac_lib_var=`echo mysqlclient'_' | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
-LIBS="-lodbc  $LIBS"
+LIBS="-lmysqlclient  $LIBS"
 cat > conftest.$ac_ext <<EOF
 #line 639 "configure"
 #include "confdefs.h"
@@ -661,23 +661,22 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  odbc_error=yes
+  mysql_error=yes
 else
   echo "$ac_t""no" 1>&6
 fi
 
-
 # Here we provide additional directories to check headers in
 # AC_CHECK_HEADERS uses CPPFLAGS to find the include path.
 #
-# If any of the headers is not in a standard place, use --with-odbc-incdir
-if test -n "${with_odbc_incdir}"; then
-   CPPFLAGS="-I${with_odbc_incdir} ${CPPFLAGS}"
-   CFLAGS="-I${with_odbc_incdir} ${CPFLAGS}"
+# If any of the headers is not in a standard place, use --with-mysql-incdir
+if test -n "${incdir}"; then
+   CPPFLAGS=" -I${incdir} ${CPPFLAGS}"
+   CFLAGS="-I${incdir} ${CPFLAGS}"
 fi
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:681: checking how to run the C preprocessor" >&5
+echo "configure:680: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -692,13 +691,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 696 "configure"
+#line 695 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:702: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:701: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -709,13 +708,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 713 "configure"
+#line 712 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:719: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:718: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -726,13 +725,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 730 "configure"
+#line 729 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:736: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:735: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -756,21 +755,21 @@ else
 fi
 echo "$ac_t""$CPP" 1>&6
 
-for ac_hdr in sql.h sqlext.h sqltypes.h
+for ac_hdr in mysql.h mysql_com.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:764: checking for $ac_hdr" >&5
+echo "configure:763: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 769 "configure"
+#line 768 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:774: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:773: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -790,18 +789,18 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   cat >> confdefs.h <<EOF
 #define $ac_tr_hdr 1
 EOF
- with_odbc=yes
+ with_mysql=yes
 else
   echo "$ac_t""no" 1>&6
-odbc_error=yes
+mysql_error=yes
 fi
 done
 
 
-if test "$odbc_error" = "yes"; then
+if test "$mysql_error" = "yes"; then
 echo ""
-echo "configure: warning:  ****Your system is missing sql.h, sqlext.h, or sqltypes.h, which are required for ODBC support
-****ODBC driver will be disabled" 1>&2
+echo "configure: warning:  ****Your system is missing mysql.h or mysql_com.h, which are required for MySQL support
+****MySQL driver will be disabled" 1>&2
 echo ""
 
 support=no
@@ -818,10 +817,11 @@ fi
 
 (
 echo ""
-echo "  ODBC support:                                   $support"
-echo "  ODBC library directory:                         $libdir"
-echo "  ODBC C Flags:                                   $CFLAGS"
-echo "  ODBC Loader Flags:                              $LDFLAGS"
+echo "  MySQL support:                                  $support"
+echo "  MySQL library directory:                        $libdir"
+echo "  MySQL header directory:                         $incdir"
+echo "  MySQL C Flags:                                  $CFLAGS"
+echo "  MySQL Loader Flags:                             $LDFLAGS"
 echo ""
 ) | tee Installation_summary
 
@@ -937,7 +937,7 @@ done
 
 ac_given_srcdir=$srcdir
 
-trap 'rm -fr `echo "odbc_init.P:odbc_init.in" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "mysql_init.P:mysql_init.in" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -1017,7 +1017,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"odbc_init.P:odbc_init.in"}
+CONFIG_FILES=\${CONFIG_FILES-"mysql_init.P:mysql_init.in"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
